import { missing, profile, projects, skills } from './data.mjs';
export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escape;
export const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>';
const tags = items => `<ul class="tags">${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
const sectionTitle = (n,title,description='') => `<div class="section-head"><div><span class="section-index">${n} /</span><h2>${title}</h2></div>${description?`<p>${description}</p>`:''}</div>`;

export function navigation() { return `<a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap nav"><a class="brand" href="#home" aria-label="Nattapong Seebudda, home">NS<span>_</span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#education">Education</a></nav><a class="nav-cta" href="#contact">Let’s connect ${arrow}</a></div></header>`; }
export function hero() { return `<section class="hero" id="home" aria-labelledby="hero-title"><div class="hero-art" role="img" aria-label="Original illustration of a futuristic city illuminated by cyan and coral lights"></div><div class="cyber-atmosphere" aria-hidden="true"><div class="cyber-glow"></div><div class="cyber-rain"></div><div class="cyber-sparks"></div></div><div class="hero-shade"></div><label class="motion-control"><input type="checkbox" id="pause-motion"><span>Pause motion</span></label><div class="wrap hero-inner"><div class="hero-copy"><h1 id="hero-title">NATTAPONG<br><span>SEEBUDDA</span><span class="cursor" aria-hidden="true">_</span></h1><p class="hero-role">Computer Engineering student.<br><strong>Building toward what’s next.</strong></p><p class="hero-description">${e(profile.introduction)}</p><div class="hero-actions"><a class="button primary" href="#projects">Explore my projects ${arrow}</a><a class="button secondary" href="#about">Get to know me <span aria-hidden="true">↓</span></a></div></div></div><div class="hero-footer wrap"><span>SOFTWARE · SYSTEMS · AI</span><a href="#about">SCROLL TO EXPLORE <span aria-hidden="true">↓</span></a></div></section>`; }
export function about() { return `<section class="section wrap" id="about">${sectionTitle('01','Curiosity, translated<br>into <span class="accent">software.</span>')}<div class="about-grid"><div class="about-text"><p class="lead">${e(profile.about)}</p><p>${e(profile.direction)}</p><ul class="strengths">${profile.strengths.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div><aside class="profile-panel" aria-label="Education at a glance"><div class="panel-top"><span>EDUCATION AT A GLANCE</span><span aria-hidden="true">↗</span></div><p class="degree">Computer Engineering<br><span>/ Internet of Things</span></p><p>${e(profile.university)}</p><div class="profile-stats"><div><strong>Year 3</strong><span>Current study year</span></div><div><strong>${e(profile.gpa)}</strong><span>Cumulative GPA / 4.00</span></div></div></aside></div></section>`; }
export function skillsSection() { return `<section class="skills-section" id="skills"><div class="wrap section">${sectionTitle('02','My working <span class="accent">toolkit.</span>','Tools I’ve used, foundations I’m studying, and areas I want to explore.')}<div class="skill-list">${skills.map((s,i)=>`<article class="skill-row"><span class="row-num">0${i+1}</span><div><h3>${e(s.title)}</h3><p>${e(s.context)}</p></div>${tags(s.items)}</article>`).join('')}</div><p class="verification-note">Skills are grouped by evidence of use. Proficiency levels: <span lang="th">${missing}</span>.</p></div></section>`; }
function projectCard(p) { return `<article class="project-card${p.id === 'payment' ? ' featured-project' : ''}" data-project="${e(p.id)}">${p.id === 'payment' ? '<p class="featured-label">FEATURED PROJECT / BUILT FROM EVERYDAY LIFE</p>' : ''}<div class="project-heading"><span class="project-number">${p.number}</span><span class="category">${e(p.category)}</span></div><h3>${e(p.name)}</h3><p class="project-short">${e(p.short)}</p><p>${e(p.description)}</p>${p.process ? `<div class="project-actions"><a class="button primary" href="${e(p.demo)}">Visit website ${arrow}</a><a class="button secondary" href="${e(p.repo)}">View repository ${arrow}</a></div><p class="repo-access">Source repository is private; access available on request.</p><div class="case-story">${p.process.map((step,i)=>`<div><span class="case-step">0${i+1}</span><h4>${e(step.title)}</h4><p>${e(step.text)}</p></div>`).join('')}</div><div class="case-debug"><h4>Where I spent time debugging</h4><p>${e(p.debugging)}</p><p>${e(p.learning)}</p><ul class="case-evidence"><li><strong>Receipt uploads</strong><span>Added upload-in-progress and failure checks before saving, with separate receipt preview handling.</span></li><li><strong>Search and filters</strong><span>Changed the expense list to use updated server data instead of retaining a stale local copy.</span></li><li><strong>Mobile layout</strong><span>Added a card-based expense list on small screens, keeping the table for larger screens.</span></li></ul></div>` : ''}${tags(p.stack)}<p class="project-status">${e(p.status)}</p><details><summary>Project notes <span aria-hidden="true">+</span></summary><div class="project-details"><dl><dt>Problem / purpose</dt><dd>${e(p.purpose)}</dd><dt>Solution</dt><dd>${e(p.solution)}</dd><dt>Features / exploration</dt><dd><ul>${p.features.map(x=>`<li>${e(x)}</li>`).join('')}</ul></dd>${p.technologies ? `<dt>Technology stack</dt><dd>${tags(p.technologies)}</dd>` : ''}${p.technical ? `<dt>Technical implementation</dt><dd><ul>${p.technical.map(x=>`<li>${e(x)}</li>`).join('')}</ul></dd>` : ''}<dt>Learning & practice</dt><dd>${e(p.learning)}</dd>${p.pending ? `<dt>Awaiting confirmation</dt><dd>${e(p.pending)}</dd>` : ''}<dt>Project links</dt><dd>${[["Repository",p.repo],["Live demo",p.demo],["Facebook page",p.page]].filter(([,url])=>url).map(([label,url])=>`<a href="${e(url)}">${label}</a>`).join(" · ") || missing}</dd></dl></div></details></article>`; }
export function projectsSection() { return `<section class="section wrap" id="projects">${sectionTitle('03','Ideas. Experiments.<br><span class="accent">Things I’ve worked on.</span>','A selection of personal projects and explorations. Open the notes for scope, technology, and what still needs confirmation.')}<div class="project-grid">${projects.map(projectCard).join('')}</div></section>`; }
export function education() { return `<section class="section wrap education" id="education">${sectionTitle('04','The engineering<br><span class="accent">foundation.</span>')}<div class="education-grid"><div class="education-main"><span class="small-label">CURRENT EDUCATION</span><h3>${e(profile.university)}</h3><p lang="th">${e(profile.universityThai)}</p><p>Third-year Computer Engineering / IoT student</p><span class="gpa">GPA <strong>${e(profile.gpa)}</strong></span><p class="verification-note">Through semester 2/2025 · 74 credits earned</p><p class="verification-note">Semester 2/2025 GPA: 3.81 · Semester 1/2026 results pending</p></div><div class="education-detail"><h3>Learning across disciplines</h3><p>Relevant coursework: Software Engineering, Database Management Systems and Data Mining, Web Applications Design and Development, Operating Systems, and Computer Architecture and Organization.</p><h3>Beyond coursework</h3><p>Personal web projects and AI-assisted content creation for “มีไรจะบอก” provide opportunities to explore technology through practice.</p><h3>Looking ahead</h3><p>Interested in postgraduate study in Computer Science, IT, or Data Science, including programs connected with King Mongkut’s University of Technology North Bangkok. This is an interest, not an admission or enrollment claim.</p></div></div></section>`; }
export function contact() { const contacts=[['Email',profile.email,'mailto:'],['GitHub',profile.github,''],['LinkedIn',profile.linkedin,''],['Resume',profile.resume,'']];return `<section class="contact-section" id="contact"><div class="wrap contact-inner"><div><span class="section-index">05 / WHAT’S NEXT</span><h2>Let’s build<br><span class="accent">what’s next.</span></h2><p>Preparing for Software Engineering Internship opportunities.<br>Interested in software development, systems, and practical AI.</p></div><div class="contact-links">${contacts.map(([label,url,prefix])=>url?`<a href="${e(prefix+url)}">${label}${arrow}</a>`:`<div class="contact-pending"><span>${label}</span><span lang="th">${missing}</span></div>`).join('')}</div></div></section>`; }
export function footer() { return `<footer class="wrap footer"><a class="brand" href="#home">NS<span>_</span></a><p>© ${new Date().getFullYear()} ${e(profile.name)}</p><a href="#home">Back to top <span aria-hidden="true">↑</span></a></footer>`; }

