export function enhancePage(html) {
  const portrait = `<div class="portrait-card"><div class="portrait-frame"><img id="profile-photo" alt="Nattapong Seebudda profile photo" hidden><div id="portrait-placeholder"><span class="portrait-monogram" aria-hidden="true">NS<span>_</span></span><p>Your photo belongs here</p></div><span class="portrait-caption">NATTAPONG / COMPUTER ENGINEERING</span></div><div class="photo-editor" hidden><label class="photo-picker" for="photo-input">Choose profile photo</label><input class="visually-hidden" id="photo-input" type="file" accept="image/jpeg,image/png,image/webp"><button id="remove-photo" type="button" hidden>Remove photo</button><p id="photo-message" role="status">Local preview only · JPG, PNG or WebP · max 3 MB</p><p class="photo-privacy">Saved only in this browser. Visitors won’t see this photo until it is added to the website files.</p></div></div>`;
  const filters = `<div class="project-tools" hidden><div class="filter-buttons" role="group" aria-label="Filter projects"><button type="button" data-filter="all" aria-pressed="true">All projects</button><button type="button" data-filter="payment" aria-pressed="false">Full-stack</button><button type="button" data-filter="automation" aria-pressed="false">AI & workflows</button></div><label class="project-search">Search projects<input id="project-search" type="search" placeholder="Try Next.js or automation" autocomplete="off"></label><p id="project-count" role="status"></p></div><div id="project-empty" hidden><h3>No matching projects</h3><p>Try another keyword or reset your filters.</p><button type="button" id="reset-filters">Reset filters</button></div>`;
  return html
    .replace('<div class="about-grid">', `<div class="about-grid">${portrait}`)
    .replace('<div class="project-grid">', `${filters}<div class="project-grid">`)
    .replace('<nav aria-label="Main navigation">', '<button id="language-toggle" type="button" aria-label="Switch to Thai" hidden>TH</button><nav aria-label="Main navigation">')
    .replace('</body>', '<script src="app.js" defer></script></body>');
}
